### ISSUE TITLE
Image in the center of the QR code

### ISSUE THREAD

**Issue by ingeJulianLasso** [mnahkies/ng-qrcode#14]
Hello, i would like to ask if it is possible to add a custom image in the center of the QR code that is generated with the library.

I have observed that this library depends on another one called "qrcode" and I consulted a little bit, I could see that it is possible to insert an image in the center of the QR code that is generated.

https://stackoverflow.com/questions/53898890/how-to-generate-qr-code-together-with-the-image-in-a-center#answers-header

Can you tell me how to do this? Thank you very much for the help you can give me

**Comment by mnahkies** [comment]
It's not something I've had need to do before, but looks quite straightforward from your link

Feel free to create a pull request, but otherwise I'll take a look in the next couple of days

**Comment by mnahkies** [comment]
Released in v4.2.0 - sorry this took so long to get around to.
