### ISSUE TITLE
Angular 12 support

### ISSUE THREAD

**Issue by Johnnyrook777** [mnahkies/ng-qrcode#25]
Update DEPs to support angular 12

**Comment by mnahkies** [comment]
In progress in https://github.com/mnahkies/ng-qrcode/pull/23 - haven't merged/released yet as I want to do a bit more testing around the `partial-ivy` change. Hope to do so this weekend

**Comment by c00** [comment]
Is there any update on this? :pray:

**Comment by mnahkies** [comment]
#23 is merged, and changes are published as `ng-qrcode@^5` - sorry for the delay, I'm hoping to automate this more before the next Angular release (already started this process by moving to github actions as part of this release)
