### ISSUE TITLE
Is it possible to access the QR image for me to add a `Download image` button?

### ISSUE THREAD

**Issue by sterichards** [mnahkies/ng-qrcode#31]
I've inspected the QR element via a browser but i'm not seeing where the data is that creates the image? 

Is there a method I could use to access the base64 string (assuming it's base64) ?

**Comment by mnahkies** [comment]
I think you should be able to do something like this:
```
  constructor(private readonly elementRef: ElementRef) {
  }

  onDownload(){
    const canvas = this.elementRef.nativeElement.querySelector('canvas')
    if(canvas){
      canvas.toBlob((blob: any) => {
        const url = URL.createObjectURL(blob);

        const anchor = document.createElement('a');
        anchor.href = url;
        anchor.target = "_blank";
        anchor.download = "qr-code.png";
        anchor.click();

        URL.revokeObjectURL(url);
      })
    }
  }

```

You might need to play around with the canvas / clone of the canvas first to get the image size right, and I think you can probably get at the `canvas` element in more elegant ways - but this should work.

**Comment by sterichards** [comment]
> private readonly elementRef: ElementRef

That's amazing. Works perfectly

Much appreciated. Thank you!
