### ISSUE TITLE
Padding and qr size

### ISSUE THREAD

**Issue by razzeee** [mnahkies/ng-qrcode#36]
Why is there so much padding?

![image](https://user-images.githubusercontent.com/5943908/135224262-39988f68-a014-45bc-9ea8-480ae348cdef.png)

When I'm setting the size to 300px I would expect that to be without padding, or is that just me?

**Comment by razzeee** [comment]
Seems like we need to set `margin: 0` or similar in the directive when calling `toCanvas`. Would you consider accepting a patch and releasing a new version for 4.0.0 too? So not just 5.0.0?

**Comment by mnahkies** [comment]
@razzeee this is a good suggestion - apologies for the delay I had a busy week. To save time back and forth I've gone ahead and implemented this but would have been happy to accept a patch as well :)

Will comment back here when I've got it into release(s).

**Comment by mnahkies** [comment]
Published in:
https://github.com/mnahkies/ng-qrcode/releases/tag/v5.1.0
https://github.com/mnahkies/ng-qrcode/releases/tag/v4.3.0
