### ISSUE TITLE
Can't install on Angular 13

### ISSUE THREAD

**Issue by ties-s** [mnahkies/ng-qrcode#43]
```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=12 <13" from ng-qrcode@5.2.0
npm ERR! node_modules/ng-qrcode
npm ERR!   ng-qrcode@"^5.0.0" from the root project
```

**Comment by mnahkies** [comment]
I'm going to wait for https://github.com/angular-eslint/angular-eslint/pull/780 to be merged/released - should happen in the next week or so.

Apologies for the delay

**Comment by mnahkies** [comment]
Released in https://github.com/mnahkies/ng-qrcode/releases/tag/v6.0.0

**Comment by ties-s** [comment]
Thanks!
