### ISSUE TITLE
Can't install on Angular 14

### ISSUE THREAD

**Issue by regazzoj** [mnahkies/ng-qrcode#59]
Hello !
Thanks for maintaining this project !
I use it in a project and when I upgrade Angular to v14, I run into a dependency problem =>
```bash
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=13 <14" from ng-qrcode@6.0.0
npm ERR! node_modules/ng-qrcode
npm ERR!   ng-qrcode@"^6.0.0" from the root project
```

I did a [PR](https://github.com/mnahkies/ng-qrcode/pull/58) to resolve this issue, if you can have a look and tell me if I need to change something.

Thanks !

**Comment by mnahkies** [comment]
Thanks for raising the PR, unfortunately I am traveling until Wednesday with no laptop so will be unable to review and release until then

**Comment by mnahkies** [comment]
Released in https://github.com/mnahkies/ng-qrcode/releases/tag/v7.0.0
