### ISSUE TITLE
Support Angular 10

### ISSUE THREAD

**Issue by silvioboehme** [mnahkies/ng-qrcode#7]
npm WARN ng-qrcode@3.1.0 requires a peer of @angular/common@>=7 <10 but none is installed. You must install peer dependencies yourself.
npm WARN ng-qrcode@3.1.0 requires a peer of @angular/core@>=7 <10 but none is installed. You must install peer dependencies yourself.
npm WARN ng-qrcode@3.1.0 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.

**Comment by mnahkies** [comment]
Will take a look tonight, thanks

**Comment by mnahkies** [comment]
Released as `ng-qrcode@4.0.1` - https://www.npmjs.com/package/ng-qrcode/v/4.0.1
