### ISSUE TITLE
Angular V17 support

### ISSUE THREAD

**Issue by serderovsh** [mnahkies/ng-qrcode#83]
Hi.
Please add support for Angular 17

**Comment by ludufre** [comment]
Hi, I've created a [PR](https://github.com/mnahkies/ng-qrcode/pull/84)

**Comment by serderovsh** [comment]
> Hi, I've created a [PR](https://github.com/mnahkies/ng-qrcode/pull/84)

Thanks YOU

**Comment by mnahkies** [comment]
Released in v17.0.0

https://github.com/mnahkies/ng-qrcode/releases/tag/v17.0.0
