### ISSUE TITLE
Upgrade to Angular 18 and above

### ISSUE THREAD

**Issue by Akxe** [mnahkies/ng-qrcode#96]
Hi, In order not to block upgrades to newer versions of Angular, you could move your Angular `dependencies` to `devEependencies`, and thus allowing users to install any version they want :)

See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/package.json for insiration.

**Comment by mnahkies** [comment]
This is actually already the case for the package itself - it specifies the angular dependencies as `peerDependencies` with version constraints based on what versions are officially supported https://github.com/mnahkies/ng-qrcode/blob/master/projects%2Fng-qrcode%2Fpackage.json#L17-L24

Most package managers will log a warning but not prevent you from going outside these constraints in my experience, though it's possible that some are stricter.

I'll be aiming to upgrade/test/release this weekend regardless.

**Comment by mnahkies** [comment]
Update to [v18 released](https://github.com/mnahkies/ng-qrcode/releases/tag/v18.0.0)
